human(alice,1).
human(edmond_dantes,1).
human(sherlock_holmes,1).
human(cheshire_cat,0).
human(harry_potter,0).
human(dartagnan,1).
human(zorro,1).
human(robin_hood,1).
human(hercule_poirot,1).
human(robinson_crusoe,1).
human(captain_nemo,1).
human(tom_sawyer,1).
human(natasha_rostova,1).
human(andrey_bolkonsky,1).
human(anna_karenina,1).
human(don_quixote,1).
human(carlson,1).
human(daisy_buchanan,1).
human(pinocchio,0).
human(moby_dick,0).
human(jane_eyre,1).
human(ostap_bender,1).
human(peter_pan,1).

human(bilbo_baggins,0).
human(hermione_granger,1).
human(dragon_smaug,0).
human(hercules,1).
human(dunno,0).
human(brave_lion,0).
human(baba_yaga,0).
human(the_wizard_of_oz,1).
human(ding_ding,0).
human(king_arthur,1).
human(scarlett_OHara,1).
human(dr_Watson,1).
human(elizabeth_bennet,1).
human(aladdin,1).
human(ron_weasley,0).
human(sinbad_the_mariner,1).
human(captain_hook,1).


female(alice,1).
female(edmond_dantes,0).
female(sherlock_holmes,0).
female(cheshire_cat,0).
female(harry_potter,0).
female(dartagnan,0).
female(zorro,0).
female(robin_hood,0).
female(hercule_poirot,0).
female(robinson_crusoe,0).
female(captain_nemo,0).
female(tom_sawyer,0).
female(natasha_rostova,1).
female(andrey_bolkonsky,0).
female(anna_karenina,1).
female(don_quixote,0).
female(carlson,0).
female(daisy_buchanan,1).
female(pinocchio,0).
female(moby_dick,0).
female(jane_eyre,1).
female(ostap_bender,0).
female(peter_pan,0).

female(bilbo_baggins,0).
female(hermione_granger,1).
female(dragon_smaug,0).
female(hercules,0).
female(dunno,0).
female(brave_lion,0).
female(baba_yaga,1).
female(the_wizard_of_oz,1).
female(ding_ding,1).
female(king_arthur,0).
female(scarlett_OHara,1).
female(dr_Watson,0).
female(elizabeth_bennet,1).
female(aladdin,0).
female(ron_weasley,0).
female(sinbad_the_mariner,0).
female(captain_hook,0).


hero(alice,0).
hero(edmond_dantes,0).
hero(sherlock_holmes,1).
hero(cheshire_cat,0).
hero(harry_potter,1).
hero(dartagnan,1).
hero(zorro,1).
hero(robin_hood,1).
hero(hercule_poirot,1).
hero(robinson_crusoe,0).
hero(captain_nemo,1).
hero(tom_sawyer,0).
hero(natasha_rostova,0).
hero(andrey_bolkonsky,1).
hero(anna_karenina,0).
hero(don_quixote,1).
hero(carlson,0).
hero(daisy_buchanan,0).
hero(pinocchio,0).
hero(moby_dick,0).
hero(jane_eyre,0).
hero(ostap_bender,0).
hero(peter_pan,0).

hero(bilbo_baggins,1).
hero(hermione_granger,1).
hero(dragon_smaug,0).
hero(hercules,1).
hero(dunno,0).
hero(brave_lion,1).
hero(baba_yaga,0).
hero(the_wizard_of_oz,0).
hero(ding_ding,0).
hero(king_arthur,1).
hero(scarlett_OHara,0).
hero(dr_Watson,1).
hero(elizabeth_bennet,0).
hero(aladdin,0).
hero(ron_weasley,1).
hero(sinbad_the_mariner,0).
hero(captain_hook,0).


children(alice,0).
children(edmond_dantes,0).
children(sherlock_holmes,0).
children(cheshire_cat,0).
children(harry_potter,1).
children(dartagnan,0).
children(zorro,1).
children(robin_hood,0).
children(hercule_poirot,0).
children(robinson_crusoe,0).
children(captain_nemo,1).
children(tom_sawyer,0).
children(natasha_rostova,1).
children(andrey_bolkonsky,1).
children(anna_karenina,1).
children(don_quixote,0).
children(carlson,0).
children(daisy_buchanan,1).
children(pinocchio,0).
children(moby_dick,0).
children(jane_eyre,1).
children(ostap_bender,0).
children(peter_pan,0).

children(bilbo_baggins,0).
children(hermione_granger,1).
children(dragon_smaug,0).
children(hercules,1).
children(dunno,0).
children(brave_lion,1).
children(baba_yaga,0).
children(the_wizard_of_oz,0).
children(ding_ding,0).
children(king_arthur,1).
children(scarlett_OHara,1).
children(dr_Watson,0).
children(elizabeth_bennet,0).
children(aladdin,0).
children(ron_weasley,1).
children(sinbad_the_mariner,0).
children(captain_hook,0).


magical(alice,1).
magical(edmond_dantes,0).
magical(sherlock_holmes,0).
magical(cheshire_cat,1).
magical(harry_potter,1).
magical(dartagnan,0).
magical(zorro,0).
magical(robin_hood,0).
magical(hercule_poirot,0).
magical(robinson_crusoe,0).
magical(captain_nemo,0).
magical(tom_sawyer,0).
magical(natasha_rostova,0).
magical(andrey_bolkonsky,0).
magical(anna_karenina,0).
magical(don_quixote,0).
magical(carlson,0).
magical(daisy_buchanan,0).
magical(pinocchio,1).
magical(moby_dick,0).
magical(jane_eyre,0).
magical(ostap_bender,0).
magical(peter_pan,1).

magical(bilbo_baggins,1).
magical(hermione_granger,1).
magical(dragon_smaug,1).
magical(hercules,0).
magical(dunno,1).
magical(brave_lion,1).
magical(baba_yaga,1).
magical(the_wizard_of_oz,1).
magical(ding_ding,1).
magical(king_arthur,0).
magical(scarlett_OHara,0).
magical(dr_Watson,0).
magical(elizabeth_bennet,0).
magical(aladdin,1).
magical(ron_weasley,1).
magical(sinbad_the_mariner,1).
magical(captain_hook,1).


voyage(alice,0).
voyage(edmond_dantes,1).
voyage(sherlock_holmes,0).
voyage(cheshire_cat,0).
voyage(harry_potter,0).
voyage(dartagnan,0).
voyage(zorro,0).
voyage(robin_hood,0).
voyage(hercule_poirot,0).
voyage(robinson_crusoe,1).
voyage(captain_nemo,1).
voyage(tom_sawyer,0).
voyage(natasha_rostova,0).
voyage(andrey_bolkonsky,0).
voyage(anna_karenina,0).
voyage(don_quixote,0).
voyage(carlson,0).
voyage(daisy_buchanan,0).
voyage(pinocchio,0).
voyage(moby_dick,0).
voyage(jane_eyre,0).
voyage(ostap_bender,0).
voyage(peter_pan,0).

voyage(bilbo_baggins,0).
voyage(hermione_granger,0).
voyage(dragon_smaug,0).
voyage(hercules,1).
voyage(dunno,0).
voyage(brave_lion,0).
voyage(baba_yaga,0).
voyage(the_wizard_of_oz,0).
voyage(ding_ding,0).
voyage(king_arthur,0).
voyage(scarlett_OHara,0).
voyage(dr_Watson,0).
voyage(elizabeth_bennet,0).
voyage(aladdin,0).
voyage(ron_weasley,0).
voyage(sinbad_the_mariner,1).
voyage(captain_hook,1).


rich(alice,0).
rich(edmond_dantes,1).
rich(sherlock_holmes,0).
rich(cheshire_cat,0).
rich(harry_potter,1).
rich(dartagnan,0).
rich(zorro,0).
rich(robin_hood,0).
rich(hercule_poirot,0).
rich(robinson_crusoe,0).
rich(captain_nemo,1).
rich(tom_sawyer,0).
rich(natasha_rostova,1).
rich(andrey_bolkonsky,1).
rich(anna_karenina,1).
rich(don_quixote,0).
rich(carlson,0).
rich(daisy_buchanan,1).
rich(pinocchio,0).
rich(moby_dick,0).
rich(jane_eyre,0).
rich(ostap_bender,0).
rich(peter_pan,0).

rich(bilbo_baggins,1).
rich(hermione_granger,0).
rich(dragon_smaug,1).
rich(hercules,1).
rich(dunno,0).
rich(brave_lion,0).
rich(baba_yaga,0).
rich(the_wizard_of_oz,0).
rich(ding_ding,0).
rich(king_arthur,1).
rich(scarlett_OHara,1).
rich(dr_Watson,0).
rich(elizabeth_bennet,1).
rich(aladdin,0).
rich(ron_weasley,0).
rich(sinbad_the_mariner,1).
rich(captain_hook,0).


crimes(alice,0).
crimes(edmond_dantes,1).
crimes(sherlock_holmes,1).
crimes(cheshire_cat,0).
crimes(harry_potter,0).
crimes(dartagnan,0).
crimes(zorro,0).
crimes(robin_hood,0).
crimes(hercule_poirot,1).
crimes(robinson_crusoe,0).
crimes(captain_nemo,0).
crimes(tom_sawyer,1).
crimes(natasha_rostova,0).
crimes(andrey_bolkonsky,0).
crimes(anna_karenina,0).
crimes(don_quixote,0).
crimes(carlson,0).
crimes(daisy_buchanan,0).
crimes(pinocchio,0).
crimes(moby_dick,0).
crimes(jane_eyre,0).
crimes(ostap_bender,0).
crimes(peter_pan,0).

crimes(bilbo_baggins,0).
crimes(hermione_granger,0).
crimes(dragon_smaug,0).
crimes(hercules,0).
crimes(dunno,0).
crimes(brave_lion,0).
crimes(baba_yaga,0).
crimes(the_wizard_of_oz,0).
crimes(ding_ding,0).
crimes(king_arthur,0).
crimes(scarlett_OHara,0).
crimes(dr_Watson,1).
crimes(elizabeth_bennet,0).
crimes(aladdin,0).
crimes(ron_weasley,0).
crimes(sinbad_the_mariner,0).
crimes(captain_hook,0).


partner(alice,0).
partner(edmond_dantes,0).
partner(sherlock_holmes,1).
partner(cheshire_cat,0).
partner(harry_potter,0).
partner(dartagnan,0).
partner(zorro,0).
partner(robin_hood,0).
partner(hercule_poirot,0).
partner(robinson_crusoe,0).
partner(captain_nemo,0).
partner(tom_sawyer,0).
partner(natasha_rostova,0).
partner(andrey_bolkonsky,0).
partner(anna_karenina,0).
partner(don_quixote,0).
partner(carlson,0).
partner(daisy_buchanan,0).
partner(pinocchio,0).
partner(moby_dick,0).
partner(jane_eyre,0).
partner(ostap_bender,1).
partner(peter_pan,0).

partner(bilbo_baggins,1).
partner(hermione_granger,0).
partner(dragon_smaug,0).
partner(hercules,0).
partner(dunno,1).
partner(brave_lion,1).
partner(baba_yaga,0).
partner(the_wizard_of_oz,0).
partner(ding_ding,0).
partner(king_arthur,0).
partner(scarlett_OHara,0).
partner(dr_Watson,1).
partner(elizabeth_bennet,0).
partner(aladdin,1).
partner(ron_weasley,0).
partner(sinbad_the_mariner,0).
partner(captain_hook,0).


wand(alice,0).
wand(edmond_dantes,0).
wand(sherlock_holmes,0).
wand(cheshire_cat,0).
wand(harry_potter,1).
wand(dartagnan,0).
wand(zorro,0).
wand(robin_hood,0).
wand(hercule_poirot,0).
wand(robinson_crusoe,0).
wand(captain_nemo,0).
wand(tom_sawyer,0).
wand(natasha_rostova,0).
wand(andrey_bolkonsky,0).
wand(anna_karenina,0).
wand(don_quixote,0).
wand(carlson,0).
wand(daisy_buchanan,0).
wand(pinocchio,0).
wand(moby_dick,0).
wand(jane_eyre,0).
wand(ostap_bender,0).
wand(peter_pan,0).

wand(bilbo_baggins,0).
wand(hermione_granger,1).
wand(dragon_smaug,0).
wand(hercules,0).
wand(dunno,0).
wand(brave_lion,0).
wand(baba_yaga,0).
wand(the_wizard_of_oz,0).
wand(ding_ding,0).
wand(king_arthur,0).
wand(scarlett_OHara,0).
wand(dr_Watson,0).
wand(elizabeth_bennet,0).
wand(aladdin,0).
wand(ron_weasley,1).
wand(sinbad_the_mariner,0).
wand(captain_hook,0).


mask(alice,0).
mask(edmond_dantes,0).
mask(sherlock_holmes,0).
mask(cheshire_cat,0).
mask(harry_potter,0).
mask(dartagnan,0).
mask(zorro,1).
mask(robin_hood,0).
mask(hercule_poirot,0).
mask(robinson_crusoe,0).
mask(captain_nemo,0).
mask(tom_sawyer,0).
mask(natasha_rostova,0).
mask(andrey_bolkonsky,0).
mask(anna_karenina,0).
mask(don_quixote,0).
mask(carlson,0).
mask(daisy_buchanan,0).
mask(pinocchio,0).
mask(moby_dick,0).
mask(jane_eyre,0).
mask(ostap_bender,0).
mask(peter_pan,0).

mask(bilbo_baggins,0).
mask(hermione_granger,0).
mask(dragon_smaug,0).
mask(hercules,0).
mask(dunno,0).
mask(brave_lion,0).
mask(baba_yaga,0).
mask(the_wizard_of_oz,0).
mask(ding_ding,0).
mask(king_arthur,0).
mask(scarlett_OHara,0).
mask(dr_Watson,0).
mask(elizabeth_bennet,0).
mask(aladdin,0).
mask(ron_weasley,0).
mask(sinbad_the_mariner,0).
mask(captain_hook,0).


treasure(alice,0).
treasure(edmond_dantes,1).
treasure(sherlock_holmes,0).
treasure(cheshire_cat,0).
treasure(harry_potter,0).
treasure(dartagnan,0).
treasure(zorro,0).
treasure(robin_hood,0).
treasure(hercule_poirot,0).
treasure(robinson_crusoe,0).
treasure(captain_nemo,1).
treasure(tom_sawyer,1).
treasure(natasha_rostova,0).
treasure(andrey_bolkonsky,0).
treasure(anna_karenina,0).
treasure(don_quixote,0).
treasure(carlson,0).
treasure(daisy_buchanan,0).
treasure(pinocchio,1).
treasure(moby_dick,0).
treasure(jane_eyre,0).
treasure(ostap_bender,1).
treasure(peter_pan,0).

treasure(bilbo_baggins,1).
treasure(hermione_granger,0).
treasure(dragon_smaug,0).
treasure(hercules,0).
treasure(dunno,0).
treasure(brave_lion,0).
treasure(baba_yaga,0).
treasure(the_wizard_of_oz,0).
treasure(ding_ding,0).
treasure(king_arthur,0).
treasure(scarlett_OHara,0).
treasure(dr_Watson,0).
treasure(elizabeth_bennet,0).
treasure(aladdin,1).
treasure(ron_weasley,0).
treasure(sinbad_the_mariner,1).
treasure(captain_hook,1).


tragic(alice,0).
tragic(edmond_dantes,1).
tragic(sherlock_holmes,0).
tragic(cheshire_cat,0).
tragic(harry_potter,0).
tragic(dartagnan,0).
tragic(zorro,0).
tragic(robin_hood,1).
tragic(hercule_poirot,0).
tragic(robinson_crusoe,1).
tragic(captain_nemo,0).
tragic(tom_sawyer,0).
tragic(natasha_rostova,1).
tragic(andrey_bolkonsky,1).
tragic(anna_karenina,1).
tragic(don_quixote,1).
tragic(carlson,0).
tragic(daisy_buchanan,1).
tragic(pinocchio,0).
tragic(moby_dick,1).
tragic(jane_eyre,1).
tragic(ostap_bender,1).
tragic(peter_pan,0).

tragic(bilbo_baggins,0).
tragic(hermione_granger,0).
tragic(dragon_smaug,1).
tragic(hercules,1).
tragic(dunno,0).
tragic(brave_lion,0).
tragic(baba_yaga,0).
tragic(the_wizard_of_oz,0).
tragic(ding_ding,0).
tragic(king_arthur,1).
tragic(scarlett_OHara,1).
tragic(dr_Watson,1).
tragic(elizabeth_bennet,1).
tragic(aladdin,0).
tragic(ron_weasley,0).
tragic(sinbad_the_mariner,0).
tragic(captain_hook,1).


legends(alice,0).
legends(edmond_dantes,0).
legends(sherlock_holmes,0).
legends(cheshire_cat,0).
legends(harry_potter,1).
legends(dartagnan,1).
legends(zorro,1).
legends(robin_hood,1).
legends(hercule_poirot,0).
legends(robinson_crusoe,0).
legends(captain_nemo,0).
legends(tom_sawyer,0).
legends(natasha_rostova,0).
legends(andrey_bolkonsky,0).
legends(anna_karenina,0).
legends(don_quixote,0).
legends(carlson,0).
legends(daisy_buchanan,0).
legends(pinocchio,0).
legends(moby_dick,1).
legends(jane_eyre,0).
legends(ostap_bender,0).
legends(peter_pan,1).

legends(bilbo_baggins,1).
legends(hermione_granger,0).
legends(dragon_smaug,1).
legends(hercules,1).
legends(dunno,0).
legends(brave_lion,0).
legends(baba_yaga,1).
legends(the_wizard_of_oz,1).
legends(ding_ding,0).
legends(king_arthur,1).
legends(scarlett_OHara,0).
legends(dr_Watson,0).
legends(elizabeth_bennet,0).
legends(aladdin,1).
legends(ron_weasley,0).
legends(sinbad_the_mariner,1).
legends(captain_hook,0).


fly(alice,0).
fly(edmond_dantes,0).
fly(sherlock_holmes,0).
fly(cheshire_cat,1).
fly(harry_potter,0).
fly(dartagnan,0).
fly(zorro,0).
fly(robin_hood,0).
fly(hercule_poirot,0).
fly(robinson_crusoe,0).
fly(captain_nemo,0).
fly(tom_sawyer,0).
fly(natasha_rostova,0).
fly(andrey_bolkonsky,0).
fly(anna_karenina,0).
fly(don_quixote,0).
fly(carlson,1).
fly(daisy_buchanan,0).
fly(pinocchio,0).
fly(moby_dick,0).
fly(jane_eyre,0).
fly(ostap_bender,0).
fly(peter_pan,1).

fly(bilbo_baggins,0).
fly(hermione_granger,0).
fly(dragon_smaug,1).
fly(hercules,0).
fly(dunno,0).
fly(brave_lion,0).
fly(baba_yaga,1).
fly(the_wizard_of_oz,0).
fly(ding_ding,1).
fly(king_arthur,0).
fly(scarlett_OHara,0).
fly(dr_Watson,0).
fly(elizabeth_bennet,0).
fly(aladdin,0).
fly(ron_weasley,0).
fly(sinbad_the_mariner,0).
fly(captain_hook,0).


knight(alice,0).
knight(edmond_dantes,0).
knight(sherlock_holmes,0).
knight(cheshire_cat,0).
knight(harry_potter,0).
knight(dartagnan,0).
knight(zorro,0).
knight(robin_hood,1).
knight(hercule_poirot,0).
knight(robinson_crusoe,0).
knight(captain_nemo,0).
knight(tom_sawyer,0).
knight(natasha_rostova,0).
knight(andrey_bolkonsky,0).
knight(anna_karenina,0).
knight(don_quixote,1).
knight(carlson,0).
knight(daisy_buchanan,0).
knight(pinocchio,0).
knight(moby_dick,0).
knight(jane_eyre,0).
knight(ostap_bender,0).
knight(peter_pan,0).

knight(bilbo_baggins,0).
knight(hermione_granger,0).
knight(dragon_smaug,0).
knight(hercules,0).
knight(dunno,0).
knight(brave_lion,0).
knight(baba_yaga,0).
knight(the_wizard_of_oz,0).
knight(ding_ding,0).
knight(king_arthur,1).
knight(scarlett_OHara,0).
knight(dr_Watson,0).
knight(elizabeth_bennet,0).
knight(aladdin,0).
knight(ron_weasley,0).
knight(sinbad_the_mariner,0).
knight(captain_hook,0).


battles(alice,0).
battles(edmond_dantes,0).
battles(sherlock_holmes,0).
battles(cheshire_cat,0).
battles(harry_potter,1).
battles(dartagnan,1).
battles(zorro,1).
battles(robin_hood,1).
battles(hercule_poirot,0).
battles(robinson_crusoe,0).
battles(captain_nemo,0).
battles(tom_sawyer,0).
battles(natasha_rostova,0).
battles(andrey_bolkonsky,1).
battles(anna_karenina,0).
battles(don_quixote,1).
battles(carlson,0).
battles(daisy_buchanan,0).
battles(pinocchio,0).
battles(moby_dick,0).
battles(jane_eyre,0).
battles(ostap_bender,0).
battles(peter_pan,1).

battles(bilbo_baggins,1).
battles(hermione_granger,1).
battles(dragon_smaug,1).
battles(hercules,1).
battles(dunno,0).
battles(brave_lion,1).
battles(baba_yaga,0).
battles(the_wizard_of_oz,0).
battles(ding_ding,0).
battles(king_arthur,1).
battles(scarlett_OHara,0).
battles(dr_Watson,0).
battles(elizabeth_bennet,0).
battles(aladdin,0).
battles(ron_weasley,1).
battles(sinbad_the_mariner,0).
battles(captain_hook,1).


story(alice,0).
story(edmond_dantes,0).
story(sherlock_holmes,0).
story(cheshire_cat,0).
story(harry_potter,0).
story(dartagnan,1).
story(zorro,0).
story(robin_hood,1).
story(hercule_poirot,0).
story(robinson_crusoe,0).
story(captain_nemo,0).
story(tom_sawyer,0).
story(natasha_rostova,0).
story(andrey_bolkonsky,1).
story(anna_karenina,1).
story(don_quixote,1).
story(carlson,0).
story(daisy_buchanan,0).
story(pinocchio,0).
story(moby_dick,1).
story(jane_eyre,0).
story(ostap_bender,1).
story(peter_pan,0).

story(bilbo_baggins,0).
story(hermione_granger,0).
story(dragon_smaug,1).
story(hercules,1).
story(dunno,0).
story(brave_lion,0).
story(baba_yaga,0).
story(the_wizard_of_oz,0).
story(ding_ding,0).
story(king_arthur,1).
story(scarlett_OHara,0).
story(dr_Watson,0).
story(elizabeth_bennet,0).
story(aladdin,0).
story(ron_weasley,0).
story(sinbad_the_mariner,0).
story(captain_hook,0).


bonaparte(alice,0).
bonaparte(edmond_dantes,1).
bonaparte(sherlock_holmes,0).
bonaparte(cheshire_cat,0).
bonaparte(harry_potter,0).
bonaparte(dartagnan,0).
bonaparte(zorro,0).
bonaparte(robin_hood,0).
bonaparte(hercule_poirot,0).
bonaparte(robinson_crusoe,0).
bonaparte(captain_nemo,0).
bonaparte(tom_sawyer,0).
bonaparte(natasha_rostova,1).
bonaparte(andrey_bolkonsky,1).
bonaparte(anna_karenina,0).
bonaparte(don_quixote,0).
bonaparte(carlson,0).
bonaparte(daisy_buchanan,0).
bonaparte(pinocchio,0).
bonaparte(moby_dick,0).
bonaparte(jane_eyre,0).
bonaparte(ostap_bender,0).
bonaparte(peter_pan,0).

bonaparte(bilbo_baggins,0).
bonaparte(hermione_granger,0).
bonaparte(dragon_smaug,0).
bonaparte(hercules,0).
bonaparte(dunno,0).
bonaparte(brave_lion,0).
bonaparte(baba_yaga,0).
bonaparte(the_wizard_of_oz,0).
bonaparte(ding_ding,0).
bonaparte(king_arthur,0).
bonaparte(scarlett_OHara,0).
bonaparte(dr_Watson,0).
bonaparte(elizabeth_bennet,0).
bonaparte(aladdin,0).
bonaparte(ron_weasley,0).
bonaparte(sinbad_the_mariner,0).
bonaparte(captain_hook,0).


mustache(alice,0).
mustache(edmond_dantes,0).
mustache(sherlock_holmes,0).
mustache(cheshire_cat,0).
mustache(harry_potter,0).
mustache(dartagnan,1).
mustache(zorro,0).
mustache(robin_hood,0).
mustache(hercule_poirot,1).
mustache(robinson_crusoe,1).
mustache(captain_nemo,1).
mustache(tom_sawyer,0).
mustache(natasha_rostova,0).
mustache(andrey_bolkonsky,0).
mustache(anna_karenina,0).
mustache(don_quixote,1).
mustache(carlson,0).
mustache(daisy_buchanan,0).
mustache(pinocchio,0).
mustache(moby_dick,0).
mustache(jane_eyre,0).
mustache(ostap_bender,1).
mustache(peter_pan,0).

mustache(bilbo_baggins,0).
mustache(hermione_granger,0).
mustache(dragon_smaug,0).
mustache(hercules,1).
mustache(dunno,0).
mustache(brave_lion,0).
mustache(baba_yaga,0).
mustache(the_wizard_of_oz,1).
mustache(ding_ding,0).
mustache(king_arthur,1).
mustache(scarlett_OHara,0).
mustache(dr_Watson,1).
mustache(elizabeth_bennet,0).
mustache(aladdin,0).
mustache(ron_weasley,0).
mustache(sinbad_the_mariner,0).
mustache(captain_hook,1).


negative(alice,0).
negative(edmond_dantes,0).
negative(sherlock_holmes,0).
negative(cheshire_cat,0).
negative(harry_potter,0).
negative(dartagnan,0).
negative(zorro,0).
negative(robin_hood,0).
negative(hercule_poirot,0).
negative(robinson_crusoe,0).
negative(captain_nemo,0).
negative(tom_sawyer,0).
negative(natasha_rostova,0).
negative(andrey_bolkonsky,0).
negative(anna_karenina,0).
negative(don_quixote,0).
negative(carlson,0).
negative(daisy_buchanan,0).
negative(pinocchio,0).
negative(moby_dick,0).
negative(jane_eyre,0).
negative(ostap_bender,0).
negative(peter_pan,0).

negative(bilbo_baggins,0).
negative(hermione_granger,0).
negative(dragon_smaug,1).
negative(hercules,0).
negative(dunno,0).
negative(brave_lion,0).
negative(baba_yaga,1).
negative(the_wizard_of_oz,0).
negative(ding_ding,0).
negative(king_arthur,0).
negative(scarlett_OHara,0).
negative(dr_Watson,0).
negative(elizabeth_bennet,0).
negative(aladdin,0).
negative(ron_weasley,0).
negative(sinbad_the_mariner,0).
negative(captain_hook,1).

